%% Biomedical & Mechanical Engineering MATLAB Setup Script
% This script sets up MATLAB environment for biomedical and mechanical engineering
% Run this script after installing MATLAB and required toolboxes

clear; clc; close all;

fprintf('🔧 Setting up MATLAB for Biomedical & Mechanical Engineering...\n');
fprintf('=' * 60); fprintf('\n');

%% Check for Required Toolboxes
required_toolboxes = {
    'Signal Processing Toolbox',
    'Image Processing Toolbox', 
    'Control System Toolbox',
    'Statistics and Machine Learning Toolbox',
    'Curve Fitting Toolbox',
    'Optimization Toolbox'
};

fprintf('📦 Checking for required toolboxes...\n');
installed_toolboxes = ver;
toolbox_names = {installed_toolboxes.Name};

missing_toolboxes = {};
for i = 1:length(required_toolboxes)
    if ~any(contains(toolbox_names, required_toolboxes{i}))
        missing_toolboxes{end+1} = required_toolboxes{i};
        fprintf('❌ Missing: %s\n', required_toolboxes{i});
    else
        fprintf('✅ Found: %s\n', required_toolboxes{i});
    end
end

if ~isempty(missing_toolboxes)
    fprintf('\n⚠️  Warning: Some toolboxes are missing. Consider installing:\n');
    for i = 1:length(missing_toolboxes)
        fprintf('   - %s\n', missing_toolboxes{i});
    end
end

%% Set up Paths
fprintf('\n📁 Setting up MATLAB paths...\n');

% Get current script directory
script_dir = fileparts(mfilename('fullpath'));
project_root = fileparts(script_dir);

% Add project directories to path
addpath(fullfile(project_root, 'matlab'));
addpath(fullfile(project_root, 'matlab', 'signal_processing'));
addpath(fullfile(project_root, 'matlab', 'image_analysis'));
addpath(fullfile(project_root, 'matlab', 'control_systems'));
addpath(fullfile(project_root, 'matlab', 'biomechanics'));

fprintf('✅ MATLAB paths configured\n');

%% Create Sample Scripts
fprintf('\n📝 Creating sample MATLAB scripts...\n');

% Signal Processing Sample
signal_script = fullfile(project_root, 'matlab', 'signal_processing', 'sample_signal_processing.m');
if ~exist(signal_script, 'file')
    create_signal_processing_sample(signal_script);
    fprintf('✅ Created signal processing sample\n');
end

% Image Analysis Sample
image_script = fullfile(project_root, 'matlab', 'image_analysis', 'sample_image_analysis.m');
if ~exist(image_script, 'file')
    create_image_analysis_sample(image_script);
    fprintf('✅ Created image analysis sample\n');
end

% Control Systems Sample
control_script = fullfile(project_root, 'matlab', 'control_systems', 'sample_control_system.m');
if ~exist(control_script, 'file')
    create_control_system_sample(control_script);
    fprintf('✅ Created control system sample\n');
end

% Biomechanics Sample
biomech_script = fullfile(project_root, 'matlab', 'biomechanics', 'sample_biomechanics.m');
if ~exist(biomech_script, 'file')
    create_biomechanics_sample(biomech_script);
    fprintf('✅ Created biomechanics sample\n');
end

%% Display Setup Summary
fprintf('\n🎉 MATLAB Setup Complete!\n');
fprintf('=' * 40); fprintf('\n');
fprintf('Available sample scripts:\n');
fprintf('  - Signal Processing: %s\n', signal_script);
fprintf('  - Image Analysis: %s\n', image_script);
fprintf('  - Control Systems: %s\n', control_script);
fprintf('  - Biomechanics: %s\n', biomech_script);
fprintf('\nNext steps:\n');
fprintf('1. Run the sample scripts to test your setup\n');
fprintf('2. Start working on your engineering projects!\n');

%% Helper Functions
function create_signal_processing_sample(filename)
    content = ['%% Sample Signal Processing for Biomedical Engineering\n' ...
               '% This script demonstrates common signal processing techniques\n\n' ...
               'clear; clc; close all;\n\n' ...
               '%% Generate sample biomedical signal (ECG-like)\n' ...
               'fs = 1000;  % Sampling frequency (Hz)\n' ...
               't = 0:1/fs:2;  % Time vector (2 seconds)\n' ...
               'f1 = 1;  % Heart rate frequency (Hz)\n' ...
               'f2 = 60;  % Power line interference (Hz)\n' ...
               '\n' ...
               '% Create ECG-like signal with noise\n' ...
               'ecg_signal = sin(2*pi*f1*t) + 0.3*sin(2*pi*f2*t) + 0.1*randn(size(t));\n' ...
               '\n' ...
               '%% Filter the signal\n' ...
               'fc = 40;  % Cutoff frequency (Hz)\n' ...
               '[b, a] = butter(4, fc/(fs/2), ''low'');\n' ...
               'filtered_signal = filtfilt(b, a, ecg_signal);\n' ...
               '\n' ...
               '%% Plot results\n' ...
               'figure(''Position'', [100, 100, 1200, 400]);\n' ...
               'subplot(1, 2, 1);\n' ...
               'plot(t, ecg_signal, ''b'', ''LineWidth'', 1);\n' ...
               'hold on;\n' ...
               'plot(t, filtered_signal, ''r'', ''LineWidth'', 2);\n' ...
               'xlabel(''Time (s)'');\n' ...
               'ylabel(''Amplitude'');\n' ...
               'title(''ECG Signal Processing'');\n' ...
               'legend(''Original'', ''Filtered'');\n' ...
               'grid on;\n' ...
               '\n' ...
               '%% Frequency analysis\n' ...
               'N = length(ecg_signal);\n' ...
               'f = (0:N-1)*(fs/N);\n' ...
               'fft_original = abs(fft(ecg_signal));\n' ...
               'fft_filtered = abs(fft(filtered_signal));\n' ...
               '\n' ...
               'subplot(1, 2, 2);\n' ...
               'semilogy(f(1:N/2), fft_original(1:N/2), ''b'', ''LineWidth'', 1);\n' ...
               'hold on;\n' ...
               'semilogy(f(1:N/2), fft_filtered(1:N/2), ''r'', ''LineWidth'', 2);\n' ...
               'xlabel(''Frequency (Hz)'');\n' ...
               'ylabel(''Magnitude'');\n' ...
               'title(''Frequency Spectrum'');\n' ...
               'legend(''Original'', ''Filtered'');\n' ...
               'grid on;\n' ...
               'xlim([0, 100]);\n' ...
               '\n' ...
               'fprintf(''Signal processing analysis complete!\\n'');\n'];
    
    fid = fopen(filename, 'w');
    fprintf(fid, content);
    fclose(fid);
end

function create_image_analysis_sample(filename)
    content = ['%% Sample Image Analysis for Biomedical Engineering\n' ...
               '% This script demonstrates medical image processing techniques\n\n' ...
               'clear; clc; close all;\n\n' ...
               '%% Create sample medical image (synthetic MRI-like)\n' ...
               'image_size = 256;\n' ...
               '[X, Y] = meshgrid(1:image_size, 1:image_size);\n' ...
               '\n' ...
               '% Create brain-like structure\n' ...
               'center_x = image_size/2;\n' ...
               'center_y = image_size/2;\n' ...
               'radius = 80;\n' ...
               '\n' ...
               '% Brain outline\n' ...
               'brain_mask = ((X - center_x).^2 + (Y - center_y).^2) <= radius^2;\n' ...
               '\n' ...
               '% Add some internal structures\n' ...
               'ventricle_mask = ((X - center_x).^2 + (Y - center_y).^2) <= (radius/3)^2;\n' ...
               '\n' ...
               '% Create image with different tissue types\n' ...
               'medical_image = zeros(image_size, image_size);\n' ...
               'medical_image(brain_mask) = 0.8;  % Brain tissue\n' ...
               'medical_image(ventricle_mask) = 0.2;  % Ventricles\n' ...
               '\n' ...
               '% Add noise\n' ...
               'medical_image = medical_image + 0.1*randn(image_size, image_size);\n' ...
               'medical_image = max(0, min(1, medical_image));  % Clamp to [0,1]\n' ...
               '\n' ...
               '%% Image processing\n' ...
               '% Gaussian filter for noise reduction\n' ...
               'sigma = 1.5;\n' ...
               'filtered_image = imgaussfilt(medical_image, sigma);\n' ...
               '\n' ...
               '% Edge detection\n' ...
               'edges = edge(filtered_image, ''canny'');\n' ...
               '\n' ...
               '% Segmentation using thresholding\n' ...
               'threshold = 0.5;\n' ...
               'segmented = filtered_image > threshold;\n' ...
               '\n' ...
               '%% Display results\n' ...
               'figure(''Position'', [100, 100, 1000, 600]);\n' ...
               '\n' ...
               'subplot(2, 2, 1);\n' ...
               'imshow(medical_image, []);\n' ...
               'title(''Original Medical Image'');\n' ...
               'colorbar;\n' ...
               '\n' ...
               'subplot(2, 2, 2);\n' ...
               'imshow(filtered_image, []);\n' ...
               'title(''Filtered Image'');\n' ...
               'colorbar;\n' ...
               '\n' ...
               'subplot(2, 2, 3);\n' ...
               'imshow(edges);\n' ...
               'title(''Edge Detection'');\n' ...
               '\n' ...
               'subplot(2, 2, 4);\n' ...
               'imshow(segmented);\n' ...
               'title(''Segmented Image'');\n' ...
               '\n' ...
               'fprintf(''Image analysis complete!\\n'');\n' ...
               'fprintf(''Brain area: %.1f%% of image\\n'', 100*sum(brain_mask(:))/numel(brain_mask));\n'];
    
    fid = fopen(filename, 'w');
    fprintf(fid, content);
    fclose(fid);
end

function create_control_system_sample(filename)
    content = ['%% Sample Control System for Mechanical Engineering\n' ...
               '% This script demonstrates PID control system design\n\n' ...
               'clear; clc; close all;\n\n' ...
               '%% Define plant transfer function\n' ...
               '% Example: DC motor with load\n' ...
               's = tf(''s'');\n' ...
               'K = 1;  % Motor gain\n' ...
               'tau = 0.5;  % Time constant\n' ...
               'plant = K / (tau*s + 1);\n' ...
               '\n' ...
               '%% Design PID controller\n' ...
               'Kp = 2;  % Proportional gain\n' ...
               'Ki = 1;  % Integral gain\n' ...
               'Kd = 0.1;  % Derivative gain\n' ...
               '\n' ...
               'pid_controller = pid(Kp, Ki, Kd);\n' ...
               '\n' ...
               '%% Create closed-loop system\n' ...
               'closed_loop = feedback(pid_controller * plant, 1);\n' ...
               '\n' ...
               '%% Time response analysis\n' ...
               't = 0:0.01:10;\n' ...
               'step_response = step(closed_loop, t);\n' ...
               '\n' ...
               '%% Frequency response analysis\n' ...
               'w = logspace(-1, 2, 1000);\n' ...
               '[mag, phase, wout] = bode(closed_loop, w);\n' ...
               '\n' ...
               '%% Display results\n' ...
               'figure(''Position'', [100, 100, 1200, 400]);\n' ...
               '\n' ...
               'subplot(1, 2, 1);\n' ...
               'plot(t, step_response, ''b'', ''LineWidth'', 2);\n' ...
               'xlabel(''Time (s)'');\n' ...
               'ylabel(''Amplitude'');\n' ...
               'title(''Step Response'');\n' ...
               'grid on;\n' ...
               '\n' ...
               'subplot(1, 2, 2);\n' ...
               'semilogx(wout, 20*log10(squeeze(mag)), ''r'', ''LineWidth'', 2);\n' ...
               'xlabel(''Frequency (rad/s)'');\n' ...
               'ylabel(''Magnitude (dB)'');\n' ...
               'title(''Bode Plot'');\n' ...
               'grid on;\n' ...
               '\n' ...
               '%% System analysis\n' ...
               'step_info = stepinfo(closed_loop);\n' ...
               'fprintf(''Control System Analysis:\\n'');\n' ...
               'fprintf(''Rise Time: %.3f s\\n'', step_info.RiseTime);\n' ...
               'fprintf(''Settling Time: %.3f s\\n'', step_info.SettlingTime);\n' ...
               'fprintf(''Overshoot: %.1f%%\\n'', step_info.Overshoot);\n' ...
               'fprintf(''Steady State Error: %.3f\\n'', 1 - step_info.SettlingMin);\n'];
    
    fid = fopen(filename, 'w');
    fprintf(fid, content);
    fclose(fid);
end

function create_biomechanics_sample(filename)
    content = ['%% Sample Biomechanics Analysis\n' ...
               '% This script demonstrates biomechanical modeling and analysis\n\n' ...
               'clear; clc; close all;\n\n' ...
               '%% Define biomechanical parameters\n' ...
               '% Human leg model parameters\n' ...
               'thigh_length = 0.4;  % m\n' ...
               'shank_length = 0.4;  % m\n' ...
               'foot_length = 0.25;  % m\n' ...
               '\n' ...
               'thigh_mass = 7.0;  % kg\n' ...
               'shank_mass = 3.5;  % kg\n' ...
               'foot_mass = 1.0;  % kg\n' ...
               '\n' ...
               '%% Joint angles (degrees)\n' ...
               'hip_angle = 0:5:90;  % Hip flexion\n' ...
               'knee_angle = 0:5:120;  % Knee flexion\n' ...
               'ankle_angle = -20:5:30;  % Ankle dorsiflexion/plantarflexion\n' ...
               '\n' ...
               '%% Calculate joint torques (simplified model)\n' ...
               'g = 9.81;  % Gravity (m/s^2)\n' ...
               '\n' ...
               '% Hip torque\n' ...
               'hip_torque = thigh_mass * g * thigh_length/2 * sind(hip_angle);\n' ...
               '\n' ...
               '% Knee torque\n' ...
               'knee_torque = (thigh_mass + shank_mass) * g * shank_length/2 * sind(knee_angle);\n' ...
               '\n' ...
               '% Ankle torque\n' ...
               'ankle_torque = (thigh_mass + shank_mass + foot_mass) * g * foot_length/2 * sind(ankle_angle);\n' ...
               '\n' ...
               '%% Plot joint torques\n' ...
               'figure(''Position'', [100, 100, 1200, 400]);\n' ...
               '\n' ...
               'subplot(1, 3, 1);\n' ...
               'plot(hip_angle, hip_torque, ''b-'', ''LineWidth'', 2);\n' ...
               'xlabel(''Hip Angle (degrees)'');\n' ...
               'ylabel(''Torque (Nm)'');\n' ...
               'title(''Hip Joint Torque'');\n' ...
               'grid on;\n' ...
               '\n' ...
               'subplot(1, 3, 2);\n' ...
               'plot(knee_angle, knee_torque, ''r-'', ''LineWidth'', 2);\n' ...
               'xlabel(''Knee Angle (degrees)'');\n' ...
               'ylabel(''Torque (Nm)'');\n' ...
               'title(''Knee Joint Torque'');\n' ...
               'grid on;\n' ...
               '\n' ...
               'subplot(1, 3, 3);\n' ...
               'plot(ankle_angle, ankle_torque, ''g-'', ''LineWidth'', 2);\n' ...
               'xlabel(''Ankle Angle (degrees)'');\n' ...
               'ylabel(''Torque (Nm)'');\n' ...
               'title(''Ankle Joint Torque'');\n' ...
               'grid on;\n' ...
               '\n' ...
               '%% Calculate center of mass\n' ...
               'total_mass = thigh_mass + shank_mass + foot_mass;\n' ...
               'com_thigh = thigh_length/2;\n' ...
               'com_shank = thigh_length + shank_length/2;\n' ...
               'com_foot = thigh_length + shank_length + foot_length/2;\n' ...
               '\n' ...
               'com_total = (thigh_mass*com_thigh + shank_mass*com_shank + foot_mass*com_foot) / total_mass;\n' ...
               '\n' ...
               'fprintf(''Biomechanics Analysis Results:\\n'');\n' ...
               'fprintf(''Total Leg Mass: %.1f kg\\n'', total_mass);\n' ...
               'fprintf(''Center of Mass: %.3f m from hip\\n'', com_total);\n' ...
               'fprintf(''Max Hip Torque: %.1f Nm\\n'', max(hip_torque));\n' ...
               'fprintf(''Max Knee Torque: %.1f Nm\\n'', max(knee_torque));\n' ...
               'fprintf(''Max Ankle Torque: %.1f Nm\\n'', max(ankle_torque));\n'];
    
    fid = fopen(filename, 'w');
    fprintf(fid, content);
    fclose(fid);
end

